function [trainDS,valDS,testDS] = splitDataset(imds)

%% 70% training
[trainDS,tempDS] = splitEachLabel( ...
    imds, ...
    0.70, ...
    "randomized");

%% Split remaining 30% equally
[valDS,testDS] = splitEachLabel( ...
    tempDS, ...
    0.50, ...
    "randomized");

end